before_script:
  - psql -c 'create database lists_test;' -U postgres

language: ruby
rvm:
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec